name: Publish ðŸ“¦ a new release ðŸ¦‰

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        type: 'string'
      release_note:
        description: 'Release Note'
        required: false
        type: 'string'

permissions:
  id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
  contents: write  # IMPORTANT: mandatory for making GitHub Releases

# .github/workflows/ci-cd.yml
jobs:
  build:
      name: Build distribution ðŸ“¦
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python ðŸ
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name:  Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install pypa/build ðŸ™
        run: >-
          python3 -m
          pip install
          build setuptools setuptools_scm wheel dynamic-versioning twine
          --user
      - name: Build a binary wheel and a source tarball
        env: 
          SETUPTOOLS_SCM_PRETEND_VERSION: ${{ github.event.inputs.release_version }}
        run: python3 -m build --wheel --sdist
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  testpypi-publish:
    name: Publish Python ðŸ distribution ðŸ“¦ of Wise Agents ðŸ¦‰ to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/wiseagents/
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    # retrieve your distributions here
    - name: Publish package distribution ðŸ“¦ to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v2.1.1
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.event.inputs.release_version }}'
        --repo '${{ github.repository }}'
        --notes '${{ github.event.inputs.release_note }}'
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        '${{ github.event.inputs.release_version }}' dist/**
        --repo '${{ github.repository }}'